# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compressCpp <- function(X, q, Y, s) {
    .Call('cplr_compressCpp', PACKAGE = 'cplr', X, q, Y, s)
}

