# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_sign <- function(n) {
    .Call('_cplr_r_sign', PACKAGE = 'cplr', n)
}

compressCpp <- function(X, q, y, s) {
    .Call('_cplr_compressCpp', PACKAGE = 'cplr', X, q, y, s)
}

#' @export
getDesign <- function(arr, mask, rad) {
    .Call('_cplr_getDesign', PACKAGE = 'cplr', arr, mask, rad)
}

