# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
getDesign <- function(arr, mask, rad) {
    .Call('_cplr_getDesign', PACKAGE = 'cplr', arr, mask, rad)
}

